# 基础镜像
FROM python:3.8

# 设置容器内的工作目录
WORKDIR /app

# 复制依赖文件
COPY requirements.txt .

# 安装项目依赖
RUN pip install -r requirements.txt

# 将应用程序代码复制到容器中
COPY . .

# 暴露 Flask 应用监听的端口
EXPOSE 5000

# 设置环境变量（如有需要）
# ENV MY_ENV_VAR=value

# 运行 Flask 应用
CMD ["python", "app.py"]